DIsabled generation of cucumber html report. Added test reporting to github workflow.

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -38,6 +38,15 @@ jobs:
         run: mvn --batch-mode test -Dtest="RunXGenerateLibUnitTest"
         working-directory: ./XGenerate
 
+      - name: Test Report
+        uses: phoenix-actions/test-reporting@v8
+        id: test-report               # Set ID reference for step
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: test-results
+          path: XGenerate/target/surefire-reports/TEST-*.xml
+          reporter: java-junit
+
       # Build single jar
       - name: Assemble Jar
         run: mvn --batch-mode assembly:single -DskipTests
